spring:
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari.jdbc-url: jdbc:h2:mem:~/test;MODE=MYSQL

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql